#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"
. "$HERE/_trap"

for ARG in "$@"; do
	case "$ARG" in
		-c)
			NAMESPACE=$NAMESPACE "$HERE/delete"
			;;
		--cluster)
			CLUSTER_MODE=true
			;;
	esac
done

export VERSION=1.0

kubectl create namespace "$NAMESPACE" || true

m "deploying operator to namespace \"$NAMESPACE\"..."
kubectl_apply_template "$ROOT/assets/kubernetes/cnck-operator.yaml"

m "waiting for operator to start..."
kubectl_wait_for_deployment cnck-operator
